# possible keybindings
# https://github.com/leftwm/leftwm/blob/main/leftwm-core/src/utils/xkeysym_lookup.rs

# possible commands
# https://github.com/leftwm/leftwm/blob/14bee8906d9e9c8f7afaee57c6ffcfe5bb2b6ad6/leftwm-core/src/handlers/command_handler.rs#L31

modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6"]

layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
scratchpad = []

disable_current_tag_swap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

# Navigation

    [[keybind]]
    command = "CloseWindow"
    modifier = ["modkey"]
    key = "q"

    [[keybind]]
    command = "MoveWindowUp"
    modifier = ["modkey", "Shift"]
    key = "Right"

    [[keybind]]
    command = "MoveWindowDown"
    modifier = ["modkey", "Shift"]
    key = "Left"

    [[keybind]]
    command = "FocusWindowUp"
    modifier = ["modkey"]
    key = "Up"

    [[keybind]]
    command = "FocusWindowDown"
    modifier = ["modkey"]
    key = "Down"

    [[keybind]]
    command = "ToggleFullScreen"
    modifier = ["modkey"]
    key = "f"

    [[keybind]]
    command = "ToggleFloating"
    modifier = ["modkey", "Shift"]
    key = "f"

# Tags

    [[keybind]]
    command = "SwapTags"
    modifier = ["Alt"]
    key = "Tab"

    [[keybind]]
    command = "FocusNextTag"
    modifier = ["modkey"]
    key = "Right"

    [[keybind]]
    command = "FocusPreviousTag"
    modifier = ["modkey"]
    key = "Left"

    [[keybind]]
    command = "GotoTag"
    value = "1"
    modifier = ["modkey"]
    key = "1"

    [[keybind]]
    command = "GotoTag"
    value = "2"
    modifier = ["modkey"]
    key = "2"

    [[keybind]]
    command = "GotoTag"
    value = "3"
    modifier = ["modkey"]
    key = "3"

    [[keybind]]
    command = "GotoTag"
    value = "4"
    modifier = ["modkey"]
    key = "4"

    [[keybind]]
    command = "GotoTag"
    value = "5"
    modifier = ["modkey"]
    key = "5"

    [[keybind]]
    command = "GotoTag"
    value = "6"
    modifier = ["modkey"]
    key = "6"

# Workspaces

    [[keybind]]
    command = "FocusWorkspaceNext"
    modifier = ["modkey"]
    key = "l"

    [[keybind]]
    command = "FocusWorkspacePrevious"
    modifier = ["modkey"]
    key = "h"

    [[keybind]]
    command = "MoveToLastWorkspace"
    modifier = ["modkey", "Shift"]
    key = "w"

    [[keybind]]
    command = "MoveWindowToNextWorkspace"
    modifier = ["modkey","Control"]
    key = "Left"

    [[keybind]]
    command = "MoveWindowToNextWorkspace"
    modifier = ["modkey","Control"]
    key = "Right"

# Layouts

    [[keybind]]
    command = "NextLayout"
    modifier = ["modkey"]
    key = "space"

    [[keybind]]
    command = "PreviousLayout"
    modifier = ["modkey", "Shift"]
    key = "space"

# LeftWM Commands

    [[keybind]]
    command = "Execute"
    value = "leftwm-command \"SendWindowToTag 1\" \"SendWorkspaceToTag 0 0\""
    modifier = ["modkey", "Shift"]
    key = "1"

    [[keybind]]
    command = "Execute"
    value = "leftwm-command \"SendWindowToTag 2\" \"SendWorkspaceToTag 0 1\""
    modifier = ["modkey", "Shift"]
    key = "2"

    [[keybind]]
    command = "Execute"
    value = "leftwm-command \"SendWindowToTag 3\" \"SendWorkspaceToTag 0 2\""
    modifier = ["modkey", "Shift"]
    key = "3"

    [[keybind]]
    command = "Execute"
    value = "leftwm-command \"SendWindowToTag 4\" \"SendWorkspaceToTag 0 3\""
    modifier = ["modkey", "Shift"]
    key = "4"

    [[keybind]]
    command = "Execute"
    value = "leftwm-command \"SendWindowToTag 5\" \"SendWorkspaceToTag 0 4\""
    modifier = ["modkey", "Shift"]
    key = "5"

    [[keybind]]
    command = "Execute"
    value = "leftwm-command \"SendWindowToTag 6\" \"SendWorkspaceToTag 0 5\""
    modifier = ["modkey", "Shift"]
    key = "6"

# Apps

    [[keybind]]
    command = "Execute"
    value = "alacritty"
    modifier = ["modkey"]
    key = "Return"

    [[keybind]]
    value = "thunar"
    command = "Execute"
    modifier = ["modkey", "Shift"]
    key = "Return"

    [[keybind]]
    command = "Execute"
    value = "flameshot gui"
    modifier = []
    key = "Print"

    [[keybind]]
    command = "Execute"
    value = "rofi -show drun"
    modifier = ["modkey"]
    key = "d"

    [[keybind]]
    command = "Execute"
    value = "rofi-theme-selector"
    modifier = ["modkey"]
    key = "F12"

# Multimedia

    [[keybind]]
    command = "Execute"
    value = "amixer set Master 10%+"
    modifier = []
    key = "F3"

    [[keybind]]
    command = "Execute"
    value = "amixer set Master 10%-"
    modifier = []
    key = "F2"

    [[keybind]]
    command = "Execute"
    value = "amixer -D pulse set Master 1+ toggle"
    modifier = []
    key = "F1"

    [[keybind]]
    command = "Execute"
    value = "playerctl play-pause"
    modifier = []
    key = "F4"

    [[keybind]]
    command = "Execute"
    value = "playerctl next"
    modifier = []
    key = "XF86AudioNext"

    [[keybind]]
    command = "Execute"
    value = "playerctl previous"
    modifier = []
    key = "XF86AudioPrev"

    [[keybind]]
    command = "Execute"
    value = "playerctl stop"
    modifier = []
    key = "XF86AudioStop"

    [[keybind]]
    command = "Execute"
    value = "brightnessctl set +10%"
    modifier = []
    key = "F6"

    [[keybind]]
    command = "Execute"
    value = "brightnessctl set 10%-"
    modifier = []
    key = "F5"

# Misc

    [[keybind]]
    command = "Execute"
    value = "~/.config/leftwm/scripts/picom-toggle.sh"
    modifier = ["Control", "Alt"]
    key = "p"

    [[keybind]]
    command = "SoftReload"
    modifier = ["modkey", "Shift"]
    key = "r"

    [[keybind]]
    command = "HardReload"
    modifier = ["modkey", "Shift"]
    key = "b"
