[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#222222"
foreground = "#F9F9F9"

[colors.search.focused_match]
background = "#ef8645"
foreground = "#000000"

[font]
size = 14

[font.bold]
family = "ShureTechMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ShureTechMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ShureTechMono Nerd Font"
style = "Italic"

[font.normal]
family = "ShureTechMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "S"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "Up"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "Down"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "Up"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "Down"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "Left"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "Right"
mode = "Search|~Vi"

[scrolling]
history = 10000
multiplier = 5

[window]
decorations = "none"
opacity = 0.4

[window.padding]
x = 15
y = 15
